<?php
/*** 
 *    ________ ____  _____      __ 
 *    \_____  \\   \/  /  \    /  \
 *      _(__  < \     /\   \/\/   /
 *     /       \/     \ \        / 
 *    /______  /___/\  \ \__/\  /  
 *           \/      \_/      \/   
 * 
 *      Trois admin v 1.0.1
 * 
 *      Copyright 2013 3xw, GmbH
 *      Belmont - Switzerland
 *      made by cousteau
 *
 *
 */

App::uses('TroisAppModel', 'Trois.Model');
class AppModel extends TroisAppModel {
}
